name: olas_hello_world
author: valory
version: 0.1.0
description: This is my awesome hello world service.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiapubcoersqnsnh3acia5hd7otzt7kjxekr6gkbrlumv6tkajl6jm
fingerprint_ignore_patterns: []
agent: valory/olas_hello_world:0.1.0:bafybeigh54vwypnmvrcyphwhzshr6ubunrbggwm5dekdbohiww6on5opsq
number_of_agents: 1
deployment: {}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    gnosis:
      address: ${GNOSIS_LEDGER_RPC:str:http://localhost:8545}
      chain_id: ${GNOSIS_CHAIN_ID:int:100}
      poa_chain: ${IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
---
public_id: valory/configs:0.19.0
type: connection
config:
  MY_API_KEY: ${MY_API_KEY:str:yyyyyyyy}
  SAFE_CONTRACT_ADDRESSES: ${SAFE_CONTRACT_ADDRESSES:str:0x0000000000000000000000000000000000000000}